# Generated by Django 4.0.4 on 2022-04-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='img',
            field=models.ImageField(default='empty.jpg', upload_to='media/robot'),
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('dof_1', models.IntegerField(blank=True)),
                ('dof_2', models.IntegerField(blank=True)),
                ('dof_3', models.IntegerField(blank=True)),
                ('dof_4', models.IntegerField(blank=True)),
                ('dof_5', models.IntegerField(blank=True)),
                ('dof_6', models.IntegerField(blank=True)),
                ('action', models.IntegerField(choices=[(0, 'Test'), (1, 'Grab the Glass')], default=0)),
                ('robot_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.robot')),
            ],
        ),
    ]
