# Generated by Django 4.0.4 on 2022-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_robotevent_dof_1_alter_robotevent_dof_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='desc_construction',
            field=models.TextField(default='Replace the text here'),
        ),
        migrations.AddField(
            model_name='robot',
            name='desc_hardware',
            field=models.TextField(default='Replace the text here'),
        ),
        migrations.AddField(
            model_name='robot',
            name='img_circuit',
            field=models.ImageField(default='empty.jpg', upload_to='media/circuit_img'),
        ),
        migrations.AddField(
            model_name='robot',
            name='url_cad_files',
            field=models.URLField(blank='True', default='https://www.thingiverse.com/'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='dof',
            field=models.IntegerField(default=0),
        ),
    ]
